# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Cluters_espaciales',
                'doc_host': 'https://msalazarcgeo.github.io',
                'git_url': 'https://github.com/msalazarcgeo/Cluters_espaciales',
                'lib_path': 'Cluters_espaciales'},
  'syms': {'Cluters_espaciales.core': {'Cluters_espaciales.core.foo': ('core.html#foo', 'Cluters_espaciales/core.py')}}}
